server:
  port: 8023
spring:
  #给项目来个名字
  application:
    name: producer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 8.142.156.127
    port: 5672
    username: admin
    password: wxy0715..
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /
    #确认消息已发送到交换机(Exchange)
    #publisher-confirms: true
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true