package com.wxy.shardingjdbc.model;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.id
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.userId
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.name
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.name_plain
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    private String namePlain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_1.name_encrypt
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    private String nameEncrypt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.id
     *
     * @return the value of t_order_1.id
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.id
     *
     * @param id the value for t_order_1.id
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.userId
     *
     * @return the value of t_order_1.userId
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.userId
     *
     * @param userid the value for t_order_1.userId
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.name
     *
     * @return the value of t_order_1.name
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.name
     *
     * @param name the value for t_order_1.name
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.name_plain
     *
     * @return the value of t_order_1.name_plain
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    public String getNamePlain() {
        return namePlain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.name_plain
     *
     * @param namePlain the value for t_order_1.name_plain
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    public void setNamePlain(String namePlain) {
        this.namePlain = namePlain == null ? null : namePlain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_1.name_encrypt
     *
     * @return the value of t_order_1.name_encrypt
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    public String getNameEncrypt() {
        return nameEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_1.name_encrypt
     *
     * @param nameEncrypt the value for t_order_1.name_encrypt
     *
     * @mbg.generated Wed Jan 04 22:04:38 CST 2023
     */
    public void setNameEncrypt(String nameEncrypt) {
        this.nameEncrypt = nameEncrypt == null ? null : nameEncrypt.trim();
    }
}