package com.wxy.shardingjdbc.model;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name_plain
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    private String namePlain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.name_encrypt
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    private String nameEncrypt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.shadow
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    private Integer shadow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name
     *
     * @return the value of test.name
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name
     *
     * @param name the value for test.name
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name_plain
     *
     * @return the value of test.name_plain
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    public String getNamePlain() {
        return namePlain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name_plain
     *
     * @param namePlain the value for test.name_plain
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    public void setNamePlain(String namePlain) {
        this.namePlain = namePlain == null ? null : namePlain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.name_encrypt
     *
     * @return the value of test.name_encrypt
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    public String getNameEncrypt() {
        return nameEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.name_encrypt
     *
     * @param nameEncrypt the value for test.name_encrypt
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    public void setNameEncrypt(String nameEncrypt) {
        this.nameEncrypt = nameEncrypt == null ? null : nameEncrypt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.shadow
     *
     * @return the value of test.shadow
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    public Integer getShadow() {
        return shadow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.shadow
     *
     * @param shadow the value for test.shadow
     *
     * @mbg.generated Thu Jan 05 10:52:28 CST 2023
     */
    public void setShadow(Integer shadow) {
        this.shadow = shadow;
    }
}