mybatis-plus:
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  checkConfigLocation: false
  global-config:
    db-config:
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      idType: ASSIGN_ID
      logic-delete-field: available # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 'NO'
      logic-not-delete-value: 'YES'
      insertStrategy: NOT_NULL
      updateStrategy: NOT_NULL
      where-strategy: NOT_NULL
  configuration:
    database-id: mysql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:/com/wxy/**/*.xml

tlog:
  pattern: "[${spring.application.name}][127.0.0.1][$spanId][$traceId]"

spring:
  profiles:
    active: dev
  application:
    name: user1

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000