CREATE TABLE IF NOT EXISTS "FILE_DETAIL"
(
    "ID" BIGINT DEFAULT 0 NOT NULL,
    "URL" NVARCHAR(512 CHAR) DEFAULT '' NOT NULL,
"SIZE" BIGINT DEFAULT 0,
"FILENAME" NVARCHAR(256 CHAR) DEFAULT '',
"ORIGINAL_FILENAME" NVARCHAR(256 CHAR) DEFAULT '',
"BASE_PATH" NVARCHAR(256 CHAR) DEFAULT '',
"PATH" NVARCHAR(256 CHAR) DEFAULT '',
"EXT" NVARCHAR(32 CHAR) DEFAULT '',
"CONTENT_TYPE" NVARCHAR(255 CHAR) DEFAULT '',
"PLATFORM" NVARCHAR(32 CHAR) DEFAULT '',
"TH_URL" NVARCHAR(512 CHAR) DEFAULT '',
"TH_FILENAME" NVARCHAR(256 CHAR) DEFAULT NULL,
"TH_SIZE" BIGINT DEFAULT 0,
"TH_CONTENT_TYPE" NVARCHAR(32 CHAR) DEFAULT '',
"OBJECT_ID" NVARCHAR(32 CHAR) DEFAULT '',
"OBJECT_TYPE" NVARCHAR(32 CHAR) DEFAULT '',
"ATTR" TEXT,
"CREATE_TIME" DATETIME(6) DEFAULT GETDATE(),
"METADATA" TEXT,
"USER_METADATA" TEXT,
"TH_METADATA" TEXT,
"TH_USER_METADATA" TEXT,
"FILE_ACL" NVARCHAR(32 CHAR) DEFAULT '',
"TH_FILE_ACL" NVARCHAR(32 CHAR) DEFAULT '',
"HASH_INFO" TEXT,
"UPLOAD_ID" NVARCHAR(128 CHAR) DEFAULT '',
"UPLOAD_STATUS" INT DEFAULT 0,
NOT CLUSTER PRIMARY KEY("ID")
);

CREATE  INDEX "IDX_OBJECT_ID" ON "FILE_DETAIL"("OBJECT_ID" ASC);
CREATE  INDEX "IDX_OBJECT_TYPE" ON "FILE_DETAIL"("OBJECT_TYPE" ASC);

CREATE TABLE IF NOT EXISTS "FILE_PART_DETAIL"
(
    "ID" NVARCHAR(32 CHAR) DEFAULT '' NOT NULL,
"PLATFORM" NVARCHAR(32 CHAR) DEFAULT '',
"UPLOAD_ID" NVARCHAR(128 CHAR) DEFAULT '',
"E_TAG" NVARCHAR(255 CHAR) DEFAULT '',
"PART_NUMBER" INT DEFAULT 0,
"PART_SIZE" BIGINT DEFAULT 0,
"HASH_INFO" TEXT,
"CREATE_TIME" DATETIME(6),
NOT CLUSTER PRIMARY KEY("ID")) ;

