CREATE TABLE IF NOT EXISTS "T_INSTANCE" (
    "ID"                BIGINT              NOT NULL COMMENT 'ID',
    "INSTANCENAME"      VARCHAR2(200)       NULL COMMENT '实例名称',
    "INSTANCEKEY"       VARCHAR2(3000)      NULL COMMENT '实例密钥',
    "ISENABLE"          SMALLINT            DEFAULT 0 NULL COMMENT '是否可用',
    "CREATOR"           BIGINT              DEFAULT NULL COMMENT '创建人id',
    "UPDATER"           BIGINT              DEFAULT NULL COMMENT '更新人id',
    "REMARK"            VARCHAR2(256)       DEFAULT NULL COMMENT '备注',
    "AVAILABLE"         VARCHAR2(3)         NOT NULL DEFAULT 'YES' COMMENT '逻辑删除',
    "CREATE_DATE"       TIMESTAMP           DEFAULT CURRENT_TIMESTAMP    NOT NULL COMMENT '创建时间',
    "UPDATE_DATE"       TIMESTAMP           DEFAULT CURRENT_TIMESTAMP    NOT NULL COMMENT '更新时间',
    "VERSION_DATE"      TIMESTAMP(3)        DEFAULT CURRENT_TIMESTAMP(3) NOT NULL COMMENT '乐观锁',
    PRIMARY KEY("ID")
);
COMMENT ON TABLE "T_INSTANCE" IS '实例表';


CREATE TABLE IF NOT EXISTS "T_INSTANCE_LINK" (
    "ID"                BIGINT              NOT NULL COMMENT 'ID',
    "INSTANCEID"        BIGINT              NOT NULL COMMENT '实例ID',
    "REQUESTERID"       VARCHAR2(256)       NOT NULL COMMENT '请求方ID',
    "REQUESTERKEY"      VARCHAR2(3000)      NULL COMMENT '请求方密钥',
    "ISENABLE"          SMALLINT            DEFAULT 0 NULL COMMENT '是否可用',
    "ISACTIVE"          SMALLINT            DEFAULT 0 NULL COMMENT '是否激活',
    "CREATOR"           BIGINT              DEFAULT NULL COMMENT '创建人ID',
    "UPDATER"           BIGINT              DEFAULT NULL COMMENT '更新人ID',
    "REMARK"            VARCHAR2(256)       DEFAULT NULL COMMENT '备注',
    "AVAILABLE"         VARCHAR2(3)         NOT NULL DEFAULT 'YES' COMMENT '逻辑删除',
    "CREATE_DATE"       TIMESTAMP           DEFAULT CURRENT_TIMESTAMP    NOT NULL COMMENT '创建时间',
    "UPDATE_DATE"       TIMESTAMP           DEFAULT CURRENT_TIMESTAMP    NOT NULL COMMENT '更新时间',
    "VERSION_DATE"      TIMESTAMP(3)        DEFAULT CURRENT_TIMESTAMP(3) NOT NULL COMMENT '乐观锁',
    PRIMARY KEY("ID")
);
COMMENT ON TABLE "T_INSTANCE_LINK" IS '实例链接表';
CREATE INDEX IF NOT EXISTS T_INSTANCE_LINK_REQUESTERID ON T_INSTANCE_LINK (REQUESTERID);

CREATE TABLE IF NOT EXISTS `T_EXAMPLE` (
    `ID`                BIGINT              NOT NULL COMMENT 'ID',
    `CODE`              VARCHAR(64)         DEFAULT NULL COMMENT 'CODE',
    `NAME`              VARCHAR(64)         DEFAULT NULL COMMENT 'NAME',
    `PERSON_NAME`       VARCHAR(64)         DEFAULT NULL COMMENT 'PERSON_NAME',
    `IC_CODE`           VARCHAR(64)         DEFAULT NULL COMMENT 'IC_CODE',
    `CREATOR`           BIGINT              DEFAULT NULL COMMENT '创建人ID',
    `UPDATER`           BIGINT              DEFAULT NULL COMMENT '更新人ID',
    `REMARK`            VARCHAR(256)        DEFAULT NULL COMMENT '备注',
    `AVAILABLE`         VARCHAR(3)          NOT NULL DEFAULT 'YES' COMMENT '逻辑删除',
    "CREATE_DATE"       TIMESTAMP           DEFAULT CURRENT_TIMESTAMP    NOT NULL COMMENT '创建时间',
    "UPDATE_DATE"       TIMESTAMP           DEFAULT CURRENT_TIMESTAMP    NOT NULL COMMENT '更新时间',
    "VERSION_DATE"      TIMESTAMP(3)        DEFAULT CURRENT_TIMESTAMP(3) NOT NULL COMMENT '乐观锁',
    PRIMARY KEY (`ID`),
    KEY `AVAILABLE` (`AVAILABLE`)
);
COMMENT ON TABLE "T_EXAMPLE" IS '示例表';
CREATE INDEX IF NOT EXISTS T_EXAMPLE_AVAILABLE ON T_EXAMPLE (AVAILABLE);